// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Data
{
    public partial class Certificate
    {
        public long Id { get; set; }
        public byte[] Path { get; set; }
        public byte[] Date { get; set; }
        public long? Order { get; set; }
    }
}