// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplicationManager.Data
{
    public partial class JobApplication
    {
        public long Id { get; set; }
        public long? CompanyId { get; set; }
        public byte[] JobTitle { get; set; }
        public byte[] City { get; set; }
        public byte[] Status { get; set; }
        public byte[] EmailSent { get; set; }
        public byte[] EmailConfirmation { get; set; }
        public byte[] LastPhonecall { get; set; }
        public byte[] JobInterview { get; set; }
        public byte[] JobOfferUrl { get; set; }

        public virtual Company Company { get; set; }
    }
}